theme: jekyll-theme-minimal
title: Matthias Rakotomalala
logo: /Images/photoMRakoto.jpg
description: <span style="font-size: 1.2em;">
    <a href="{{ '/' | relative_url }}">Home</a> | 
    <a href="{{ '/publications' | relative_url }}">Publications</a>
  </span>
  <br><br> Postdoctoral Researcher in Mathematics at the Technical University of Munich <br> <a href="mailto:matthias.rakotomalala@tum.de">&#9993; matthias.rakotomalala@tum.de </a>
github:
  is_user_page: false
  is_project_page: false
