theme: jekyll-theme-minimal
title: "Matthias Rakotomalala"
logo: "/Images/photoMRakoto.jpg"
description: >
  <h3><a href="/">Home</a> | 
  <a href="/publications">Publications</a></h3>
  Postdoctoral Researcher in Mathematics at the Technical University of Munich.<br>
  <a href="mailto:matthias.rakotomalala@tum.de">&#9993; matthias.rakotomalala@tum.de </a>
github:
  is_user_page: false
  is_project_page: false
